:toc: right
:icons: font

= Introduction to MapView

link:https://github.com/noexc/mapview[MapView] is an on-the-ground telemetry
reception system for
link:https://en.wikipedia.org/wiki/High-altitude_balloon[high-altitude balloon projects].
It is meant to be used by those with an interest in HAB chases, as a means of
tracking and following the balloon during a flight, as well as allowing for
both real-time and retroactive analysis over telemetry data received during the
course of a flight.

MapView is written from a standpoint that prefers stability (and correctness)
and modularity over speed and ease of installation. Because of this, setting it
up for the first time can be daunting, particularly if you are not familiar with
building, installing, and configuring Haskell packages.

It is our hope that this documentation makes the process as pain-free as
possible, but we invite and encourage questions about the process in the
link:irc://irc.freenode.net/noexc[#noexc channel on freenode].

== History

MapView began its life as a project for the University of Akron Amateur Radio
club's "HABP-*n*" series of balloon flights. These flights were conducted yearly
and there was a need for an effective and easy way to track the balloon.

Ricky Elrod, N8SQL, wrote a prototype of the project in NodeJS as an experiment,
having never coded in NodeJS. The prototype got positive feedback, but Ricky
ended up realizing that NodeJS would not be a viable platform to meet the goals
of the project. A rewrite in Haskell was started on
link:https://github.com/noexc/mapview/commit/3df37823aa9bf596406cc5dbdeed004d5a167517[January 20, 2014]
and has been in active development ever since.

Alumni and former students of the University of Akron formed a new club, the
link:https://noexc.org/[Northeast Ohio Experimenters Club], and maintenance
of MapView and related projects has continued under that name. The project
continues to be led by Ricky Elrod as new NOEXC flights incorporate new and
interesting requirements. MapView is and always will be free and open source
software and we welcome and encourage questions, contributions, and comments.

== Components

Previous versions of MapView came with several different executable, each
responsible for crunching certain kinds of data. However, this lead to us
inventing a fake IPC pipeline that did not scale well and was difficult to
configure and maintain.

MapView 3 takes a "configuration driven development" approach. That is, your
configuration file is a Haskell file which gets compiled and run. Your
configuration file **is** your MapView instance, customized exactly for your
flight.

This approach is not new. In fact, it is how the XMonad tiling window manager
works.

Here's how it works: MapView is no longer a "system." Instead, it is a library
for *creating* systems. We provide basic types to glue things together, and you
provide callbacks that work exactly how you want them to, over the data you
collect.

To make things easier for you, we provide a wide array of callbacks in the
MapView library, which you can take advantage of in your configuration. If they
don't work, you can simply write your own callback (possibly based on ours!) and
use it instead.

=== mapview: The Library

TIP: We also publish link:/haddock[haddock] documentation for this
library.

There is a common library used by all components. This includes, for example,
pieces of code for handling
link:https://en.wikipedia.org/wiki/Cyclic_redundancy_check[CRC] validation,
parsing of raw telemetry data, configuration file parsing, and datatypes and
typeclasses which are reused throughout the various components.

== Bugs, Comments, Issues

Please, please, **please** report any bugs or issues to our GitHub repositories
(mapview for the backend, mapview-psc for the frontend). We cannot fix or
discuss issues unless we know that you are having them!

General comments and questions can (and should! We don't bite!) be asked on our
link://irc.freenode.net/noexc[IRC channel], #noexc on freenode.

== Licensing

MapView and mapview-psc are both made available under the MIT license.
